### PR TITLE
Update project and documentation URLs

### PR DESCRIPTION
**Pull request by lindstro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
thanks!

**Comment by lindstro** [comment]
@hmaarrfk Can we go ahead and merge this?  https://anaconda.org/conda-forge/zfp still shows info for zfp 0.5.5.

**Comment by lindstro** [comment]
@hmaarrfk What triggers the push to anaconda.org?  This PR has yet to take effect.

**Comment by hmaarrfk** [comment]
image

**Comment by lindstro** [comment]
I do see that, but the license and links to the home page and documentation are still not up to date:
Screen Shot 2022-10-26 at 10 39 40 AM

This does not reflect the current `meta.yaml`:
```
about:
  home: https://zfp.llnl.gov
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Library for compressed numerical arrays that support high throughput read and write random access
  description: |
    zfp is an open source C/C++ library for compressed numerical arrays
    that support high throughput read and write random access. zfp also
    supports streaming compression of integer and floating-point data,
    e.g., for applications that read and write large data sets to and
    from disk. zfp is primarily written in C and C++ but also includes
    Python and Fortran bindings.
  doc_url: https://zfp.readthedocs.io/
  dev_url: https://github.com/LLNL/zfp
```
Any ideas?

**Comment by hmaarrfk** [comment]
yeah, i noticed. TBH, i don't think many are concerned about that page and this might have been a bug that went on unnoticed for so long. It may be a good issue to raise at 
https://github.com/conda-forge/conda-forge.github.io

**Pull request merged**
