### PR TITLE
Add support for C headers and libraries on all platforms

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/zfpy a review would be greatly appreciated.

I cleaned up most of the recipe, and submitted a patch upstream for the fix I introduced.

I'm hoping to be able to use the c library in the imagecodecs package.

**Comment by hmaarrfk** [comment]
Also, happy to be a maintainer if that helps!

**Comment by lindstro** [comment]
@hmaarrfk Thank you for your contribution.  Can you please clarify what this PR does?  The title mentions OpenMP, but zfpy does not yet expose the OpenMP execution policy (though the zfp C library supports this), and I haven't yet seen any related PRs that might address this.

I'm also unclear on what "add support for C library" refers to.  You have to excuse my limited knowledge of Conda and Python.  @kmpaul would be in a better position to review these changes.

**Comment by hmaarrfk** [comment]
I guess then it is mostly that I'm enabling zfp to be used as a c library with openmp support for Linux.

**Comment by hmaarrfk** [comment]
I want to dynamically link against zfp

**Comment by hmaarrfk** [comment]
I think mostly some headers might have been missing in the windows build. 

I also made it install python using modern cmake primitives, though I should triple check the windows logs.

**Comment by hmaarrfk** [comment]
1. Linking to OpenMP for the C library has been enabled on Linux.
2. The `zfp` command line utility has been added for all platforms
3. The windows `C` library and `DLL` have been added for downstream packages to use
4. `make` has been added as an explicit dependency, enabling forward compatibility with conda-forge arm and ppc64le
5. CMake 3.12 features are used to better detect the location of the python-site packages. This may help with #3

**Comment by lindstro** [comment]
> * Linking to OpenMP for the C library has been enabled on Linux.
> * The `zfp` command line utility has been added for all platforms
> * The windows `C` library and `DLL` have been added for downstream packages to use
> * `make` has been added as an explicit dependency, enabling forward compatibility with conda-forge arm and ppc64le
> * CMake 3.12 features are used to better detect the location of the python-site packages. This may help with #3

Thanks, but I'm still missing something.  Regarding the first three bullets, [zfp](https://github.com/LLNL/zfp) already is a C library with OpenMP support.  Its command-line utility is available via CMake (and also via GNU/Posix make) on all major platforms, and CMake allows building a Windows DLL (and Linux shared objects).  Perhaps the confusion stems from the separation between zfp (the main C/C++ repo) and zfpy (the Conda package that uses the zfp Python wrappers)?  Or is the purpose of this PR to make those C features available to those who use Conda to install zfpy rather than building zfp from source?

I cannot comment on the last two bullets other than extending my appreciation for making any Windows related improvements--thanks!  We currently (very conservatively) require CMake 3.4 on Windows, and our philosophy is to minimize dependencies and make zfp as painless to install as possible.  CMake 3.12 has been around for a couple of years, so maybe it's time to update this dependency, but only if it brings significant benefits.  @kmpaul, what do you think?

**Comment by hmaarrfk** [comment]
> Or is the purpose of this PR to make those C features available to those who use Conda to install zfpy rather than building zfp from source?

I guess this is the main point.

Conda-forge allows you to manage much more than just python. I use it to manage many of my C-related dependencies.

I could make the `zfp` package myself, but it would have some serious conflict with this package, especially on linux where the C headers are available from `zfpy` (even before this PR).

So, making a package `zfp` work in concert with the package `zfpy` would require a bit more organization. I think it is possible with ideas such as `split packages`, where in one recipe, we would build two outputs,

1. The C library called `zfp`
2. The Python wrappers called `zfpy`

But honestly, that is much harder to maintain, and since I want to build an other package with this, namely, `imagecodecs`, I don't mind the python dependency.

For the purposes of conda-forge, having a single package `zfpy` that gives both the C headers and the python wrappers, is fine, at least until an other enthusiastic developer decides it isn't!

Moving to `CMake` 3.12 is entirely your choice. You know you audiance better than I do. The challenge with python, is that the current path you had included in your `CMakeLists.txt` just wasn't correct for Windows, at least the way that conda packagaes it.

**Comment by kmpaul** [comment]
Sorry for the delay.  

My understanding is that the `zfpy` Conda package was created primarily because (1) a Conda package was seen as primarily supporting Python users and (2) Conda users were not seen as needing `zfp` _directly_, at that time.  If there is now a need for `zfp` directly because of non-Python Conda users wanting to use it, then I think we need to rethink the Conda `zfpy` package.  I think there are at least 2 paths forward:

1. We declare that `zfpy` *comes with* `zfp`, as it currently does.  If we do that, then I think the Conda package should build `zfp` with *all the bells and whistles*, including `zfpy`.  And, if that is the path we choose to follow, then maybe we should merge @hmaarrfk's PR and (possibly) rename the Conda package `zfp`.

2. We declare that `zfpy` is an *add-on* package that depends upon `zfp`.  If that is the path we want to follow, then I think the `zfp/python` code needs to be separated from the `zfp` source code (i.e., new repository).  Then, we can easily have separate Conda `zfp` and `zfpy` packages, with `zfpy` depending upon `zfp`.

Thoughts?  Obviously, we can continue down Path 1 for a while and then move to Path 2 later.

**Comment by kmpaul** [comment]
...I might also add that if there is no single *all the bells and whistles* build of `zfp`, then we might want to supply different `zfp` Conda packages for different configuration options.  Fewer packages is obviously more desirable.

**Comment by hmaarrfk** [comment]
I tried to do a similar splitpackage for opencv in the past.

Ultimately, it was decided to have:
1. A single feedstock
2. Two output packages
3. The "c++" package contains all the files (and is actually tripplicated for all the  versions of python)
4. The python package simply depends on the C++ package, and python.

This made it easier to maintain.

I'm happy to do that here.

Again, my main motivation is to use this with imagecodecs, an other python package, that would benefit from linking against `zfp`. So stripping the python output files isn't a high priority

**Comment by kmpaul** [comment]
I'd like to hear some feedback from @lindstro and the other core `zfp` developers on this.  @hmaarrfk: I personally feel like you can charge forward on this PR and do this.  I see no problem with fleshing out the conda package to provide *both* `zfp` and `zfpy` (though the Conda package name should probably change).  If at some later date, the `zfp` developers decide that `zfpy` should exist as a separate package, then we can make that decision, then.

**Comment by hmaarrfk** [comment]
Alright, I"ll try to work on this over the weekend.

My goal would be to:

1. Provide a package `zfp` that c maintainers could use as a dependency. This would include a `run_exports` to facilitate pinnings.
2. Provide a package `zfpy` so that python packagers could continue to depend on the old package.

**Comment by kmpaul** [comment]
I think that would be fantastic, @hmaarrfk!  Thank you!

**Comment by lindstro** [comment]
> ...I might also add that if there is no single _all the bells and whistles_ build of `zfp`, then we might want to supply different `zfp` Conda packages for different configuration options. Fewer packages is obviously more desirable.

From a build-from-source perspective, the "all bells and whistles" version of zfp would have several dependencies: CUDA, OpenMP, Fortran, Python, and Cython.  Future versions will have others, such as HIP.  I don't know how Conda handles such dependencies, but I suspect it would be difficult to package just a single zfp build that works seamlessly for our users.

**Comment by hmaarrfk** [comment]
Let me try to break things down:

- CUDA: There is a nascent effort lead by jakirkham we can ping him after that if you think that is important to your users.
- OpenMP: This has been enabled in this build. 
- Fortran: We can work on that in a followup PR.
- Python: This is now enabled in linux and OSX
- Cython: Same as python. currently working!

**Comment by hmaarrfk** [comment]
As for how conda can add new dependencies quite easily.

As for how conda-forge deals with this, I think the philosophy is:

1. conda-forge has built a system of CIs to automatically track dependencies and version incompatibilities.
2. Using this system, it is easy to make a package that "depends on everything".
3. Instead of building packages with fine grained dependencies, packages that include everything and the kitchen sink is more of the standard.

With the exception of the CUDA dependencies (which is more of a hardware dependency than software), we can include all the dependencies to make zfp a fully fledged installation.

**Comment by lindstro** [comment]
@hmaarrfk Do I understand correctly that the `zfp` package would not include any Python support but would rather expose only the `libzfp` (and `libcfp`?) library and associated headers (including C++ headers)?  The `zfpy` package would then add the Python bindings and depend on the `zfp` package, which would be installed automatically with `zfpy` so that our Python users would not have to install two packages separately?  I'm sorry if my questions are naive; I really have no experience with Conda.

**Comment by hmaarrfk** [comment]
That is exactly correct. No need to apologize. It is actually really nice to have the package authors involved in the delivery, since they know how their package is used and how best to deliver value to their users.

# User experience

## Python users

At the end of this merge:
```
conda install zfpy
```

will isntall everything needed for the user to type

```python
import zfpy
```

The recipe as is, only tests that one line of code (See the import section).

The test environment install `zfpy` only. You can see how `zfp` is automatically installed too
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=176694&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=2068

## Downstream C packagers

Downstream packagers, will be able to create other C packages, that depend on `zfp` by including the `zfp` package in their dependencies.

Unlike debian, or redhat, conda-forge doesn't bother splitting packages into `dev` or `devel` and non `devel` (there are some exceptions to this rule, but lets ignore those).

As a downstream packager, me hmaarrfk, would be allowed to uncomment:
https://github.com/conda-forge/imagecodecs-feedstock/blob/master/recipe/meta.yaml#L53

to compile with zfp as a C dependency.


# Implementation details

Picking and choosing which files go in which subpackage is slightly annoying on conda.
The general rule is:

* Everything that is *added* to the `PREFIX` is packaged in the package.

For the python module, we have two options:
1. Create 3 `zfp` packages, each one with the python module for a different version.
   - This is what I did for opencv because their build system was quite complicated.
2. Create a `zfp` pacakge without `python` installed at all and create subpackages, `zfpy` that build only the python submodule.

Because `zfp` builds are quick, and the build process is simpler, I decided to try 2 for this package.

Unfortunately, when the python packages are built in the same command as the rest of the system, it makes it a little tricky to integrate into conda-forge.

But using a standard `setup.py` file is annoying for you as the author of the package to maintain.

So my compromise was to:
* In the `zfpy` package, rebuild everything including the `zfp` c library.
* Let conda detect that the `zfp` c files were already installed, and as such, only include the python submodule in the 3 generated `zfpy` packages

**Comment by hmaarrfk** [comment]
FYI: Now that the package has passed, I would liek to try some small reorganizations, to make it easier to relate to. I'll ping you soon for a final review.

**Comment by hmaarrfk** [comment]
This seems like it has passed on my local machine. 

I hope this recipe organization makes a little more sense. It essentially adds a subsection to build the python dependency.

**Comment by ToreAad** [comment]
Hi, Nice work with the patches to the CmakeFile. This is a lot better than the hack I did to get it to work with windows.  It is nice with some additional tests in the metafile! Earlier in the thread @hmaarrfk volunteered to be a maintainer. It seems that he has more to contribute than me. I can step down to make space for him.

**Comment by kmpaul** [comment]
@ToreAad, do you *want* to step down?  You don't have to.  But if you want to relieve yourself of the "duty," we can remove your name.

**Comment by hmaarrfk** [comment]
@ToreAad i don't think it is about having more to contribute.

5 -6 people isn't that many maintainers, and can help in the future.

You shouldn't remove yourself if you don't want to.

In either case, we can leave that as a seperate PR

**Comment by ToreAad** [comment]
Ok, I see. I am happy to be involved, and would like continue as a maintainer.

**Comment by hmaarrfk** [comment]
glad to hear that. I find that often it is about finding a solution that fits your needs. The package was in great share as a python dependency!

Merging would be appreciated

**Pull request merged**
