### PR TITLE
macOS OpenMP, SPDX, Check CMake

### PR DESCRIPTION
**Pull request by ax3l**
Adds minor updates:
- OpenMP support on macOS
- check for installed CMake files
- license is BSD-3-Clause: https://github.com/LLNL/zfp/#license with a notice

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
Looks great. Thanks!

**Comment by lindstro** [comment]
@ax3l Looks good to me.  Thanks for your contribution!

**Pull request merged**
