### PR TITLE
Update to python3.10 and fix cross-cython

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is an update to #22 that fixes the cross-compilation using a similar hack to https://github.com/conda-forge/shapely-feedstock/blob/master/recipe/build.sh#L6-L10 .

To be honest, I don't understand how or why this works, this is just cargo-culting from @isuruf 's work.  

What is even more mysterious is the question of how the cross-build of zfpy ever worked in the first place.  After a bunch of digging I could not figure out what changed.

### CODE REVIEW

**Comment by erykoff** [comment]
Oh I am so sad now.  This works with osx-arm64 (where I was testing it), but apparently the ppc64le failure is different.

**Comment by hmaarrfk** [comment]
Honestly, I think FindPython needs to be updated.

Scikit-build is lagging a little on this:
https://github.com/LLNL/zfp/issues/110

Why not turn off cross-compilation for ppc64le?

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
frack your silly account @erykoff 

please rerender locally.

**Pull request closed without merging**
